name: Build MS Plug In App

on:
  workflow_dispatch: # Chỉ chạy khi bấm kích hoạt thủ công

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Configure CMake for iOS
      run: |
        cmake -B build -G Xcode \
          -DCMAKE_SYSTEM_NAME=iOS \
          -DCMAKE_OSX_SYSROOT=iphoneos

    - name: Build App Executable
      run: cmake --build build --config Release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSPlugIn-Build1
        path: build/Release-iphoneos/MSPlugIn.app